import { useMemo } from 'react';
import { useNavigate } from '@tanstack/react-router';
import { useQueries } from '@tanstack/react-query';
import { Hammer } from 'lucide-react';
import type { WorkOrder } from '@living/types';
import { Card, type Column, DataTable, EmptyState } from '@living/ui';

import { living } from '../../lib/living';
import { PriorityPill, StatusPill } from '../operations';
import { WO_TONES } from '../work-orders/config';
import { usePlanRuns } from './queries';

/** Work orders generated by this plan — reuses the shared table + WO badges.
 *  Execution stays in the Work Order module; rows open there. */
export function PlanWorkOrders({ planId }: { planId: string }) {
  const navigate = useNavigate();
  const runsQ = usePlanRuns(planId);

  const workOrderIds = useMemo(() => {
    const ids = (runsQ.data ?? []).filter((r) => r.generatedWorkOrderId).map((r) => r.generatedWorkOrderId!);
    return Array.from(new Set(ids)).slice(0, 50);
  }, [runsQ.data]);

  const results = useQueries({
    queries: workOrderIds.map((id) => ({
      queryKey: ['work-order', id],
      queryFn: () => living.workOrder.get(id),
      staleTime: 60_000,
    })),
  });
  const workOrders = results.map((r) => r.data).filter((w): w is WorkOrder => !!w);
  const loading = runsQ.isLoading || results.some((r) => r.isLoading);

  const columns: Column<WorkOrder>[] = [
    { key: 'number', header: 'Work order', cell: (w) => <span className="font-mono text-sm font-medium text-strong">{w.workOrderNumber}</span> },
    { key: 'title', header: 'Title', cell: (w) => <span className="truncate text-sm text-body">{w.title}</span> },
    { key: 'priority', header: 'Priority', cell: (w) => <PriorityPill priority={w.priority} /> },
    { key: 'status', header: 'Status', cell: (w) => <StatusPill status={w.status} tones={WO_TONES} /> },
  ];

  if (!loading && workOrders.length === 0) {
    return <EmptyState icon={Hammer} title="No work orders yet" description="When this plan is due, the engine generates a work order — it will appear here." />;
  }

  return (
    <Card variant="elevated" padded={false} className="overflow-hidden">
      <DataTable columns={columns} rows={workOrders} rowKey={(w) => w.id} loading={loading} onRowClick={(w) => navigate({ to: `/work-orders/${w.id}` })} />
    </Card>
  );
}
